# Generated by Django 3.2.2 on 2021-05-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='click',
            field=models.IntegerField(default=0),
        ),
    ]
