# Generated by Django 3.2.2 on 2021-05-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_alter_url_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='hash_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
